### ISSUE TITLE
Div overlay when image load slowly

### ISSUE THREAD

**Issue by ghost** [MaxLawrence/Pinto#3]
i got image inside of div,
when the image load on slow internet, the div was overlay others.
i need to resize the window to make it look nice..
thanks (and sorry for bad english)

**Comment by MaxLawrence** [comment]
It happens when you use dynamic content or images in blocks.  You should
use imageloaded plugin for images
(https://github.com/desandro/imagesloaded) or something similer.

$(".container").imagesLoaded( function() {
         // images have loaded
         $(".container").pinto({
             itemSelector:".block",
             itemWidth:250
         });
});


Also I released new version (1.2.0) where I add methods:
$(".container").pinto("layout") and $(".container").pinto("destroy").
You can use "layout" method after dynamic content load.
