### ISSUE TITLE
Divs are overlapping vertically when the page is refreshed

### ISSUE THREAD

**Issue by Inweco** [MaxLawrence/Pinto#4]
First of all, great plugin. I really love it except for one issue
Everything works just fine when the page is loaded for the first time. But if you then click on refresh, it messes things up. The different divs inside the container div seem to be overlapping horizontally and i cna not figure out why ( just a few of them and not all). Any idea on how to get this fixed?
Thank you very much for your time and effort in advance.

**Comment by urisito** [comment]
^ I agree with this guy, awesome simple plugin. Really nice job thinking everything. but i am having the same exact problem. The first time the page loads the items overlap as follows:
<img width="1321" alt="screen shot 2015-09-01 at 2 36 37 pm" src="https://cloud.githubusercontent.com/assets/5688248/9614396/4581d98e-50b7-11e5-983a-d46feab1c4cb.png">
... this is how it looks AFTER you resize the screen:
<img width="1317" alt="screen shot 2015-09-01 at 2 36 46 pm" src="https://cloud.githubusercontent.com/assets/5688248/9614429/63466ef8-50b7-11e5-9fa2-ff6d271426b5.png">
I thought the problem was that i was creating the content and then linking the js, or the order of the js, no results. Thank you for your help in advance as well haha.

**Comment by MaxLawrence** [comment]
It happens when you use dynamic content or images in blocks.  You should 
use imageloaded plugin for images 
(https://github.com/desandro/imagesloaded) or something similer.

$(".container").imagesLoaded( function() {
         // images have loaded
         $(".container").pinto({
             itemSelector:".block",
             itemWidth:250
         });
});


Also I released new version (1.2.0) where I add methods: 
$(".container").pinto("layout") and $(".container").pinto("destroy").
You can use "layout" method after dynamic content load.

01.09.2015 22:42, Uriel Escorcia пишет:
>
> ^ I agree with this guy, awesome simple plugin. Really nice job 
> thinking everything. but i am having the same exact problem. The first 
> time the page loads the items overlap as follows:
> screen shot 2015-09-01 at 2 36 37 pm 
> <https://cloud.githubusercontent.com/assets/5688248/9614396/4581d98e-50b7-11e5-983a-d46feab1c4cb.png>
> ... this is how it looks AFTER you resize the screen:
> screen shot 2015-09-01 at 2 36 46 pm 
> <https://cloud.githubusercontent.com/assets/5688248/9614429/63466ef8-50b7-11e5-9fa2-ff6d271426b5.png>
> I thought the problem was that i was creating the content and then 
> linking the js, or the order of the js, no results. Thank you for your 
> help in advance as well haha.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MaxLawrence/Pinto/issues/4#issuecomment-136837339>.
>



---
Это сообщение проверено на вирусы антивирусом Avast.
http://www.avast.com
